# NOTE, this is an EXAMPLE of a bad workflow that exposes secrets to forks
# The example is mostly safe because I've locked down PRs to only ppl with write access and
#   set Actions to require manual approval for all external contributions
# GitHub as also hardened things like pull_request_target and actions/checkout in 2026

name: PR Build & Comment

on:
  pull_request_target:
    types: [opened, synchronize]

# WARNING: This workflow should have manually set permissions, but it doesn't

jobs:
  build-and-comment:
    runs-on: ubuntu-latest
    steps:
      # ⚠️ Checks out the UNTRUSTED code from the fork...
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      # ⚠️ ...then executes it, while secrets are in scope
      - name: Install & build
        run: npm ci && npm run build

      - name: Comment result
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Build complete ✅'
            })
